export const CREATE_MENU_ITEM_REQUEST = 'CREATE_MENU_ITEM_REQUEST'
export const CREATE_MENU_ITEM_SUCCESS = 'CREATE_MENU_ITEM_SUCCESS'
export const CREATE_MENU_ITEM_FAILURE = 'CREATE_MENU_ITEM_FAILURE'

export const GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST = 'GET_MENU_ITEMS_BY_RESTAURANT_ID_REQUEST'
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS = 'GET_MENU_ITEMS_BY_RESTAURANT_ID_SUCCESS'
export const GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE = 'GET_MENU_ITEMS_BY_RESTAURANT_ID_FAILURE'

export const DELETE_MENU_ITEM_REQUEST = 'DELETE_MENU_ITEM_REQUEST'
export const DELETE_MENU_ITEM_SUCCESS = 'DELETE_MENU_ITEM_SUCCESS'
export const DELETE_MENU_ITEM_FAILURE = 'DELETE_MENU_ITEM_FAILURE'


export const SEARCH_MENU_ITEM_REQUEST = 'SEARCH_MENU_ITEM_REQUEST'
export const SEARCH_MENU_ITEM_SUCCESS = 'SEARCH_MENU_ITEM_SUCCESS'
export const SEARCH_MENU_ITEM_FAILURE = 'SEARCH_MENU_ITEM_FAILURE'


export const UPDATE_MENU_ITEM_AVALIABLE_REQUEST = 'UPDATE_MENU_ITEM_AVALIABLE_REQUEST'
export const UPDATE_MENU_ITEM_AVALIABLE_SUCCESS = 'UPDATE_MENU_ITEM_AVALIABLE_SUCCESS'
export const UPDATE_MENU_ITEM_AVALIABLE_FAILURE = 'UPDATE_MENU_ITEM_AVALIABLE_FAILURE'

export const GET_ALL_DRINK_OF_RESTAURANT_REQUEST = 'GET_ALL_DRINK_OF_RESTAURANT_REQUEST'
export const GET_ALL_DRINK_OF_RESTAURANT_SUCCESS = 'GET_ALL_DRINK_OF_RESTAURANT_SUCCESS'
export const GET_ALL_DRINK_OF_RESTAURANT_FAILURE = 'GET_ALL_DRINK_OF_RESTAURANT_FAILURE'

export const UPDATE_DISCOUNT_DRINK_REQUEST = 'UPDATE_DISCOUNT_DRINK_REQUEST'
export const UPDATE_DISCOUNT_DRINK_SUCCESS = 'UPDATE_DISCOUNT_DRINK_SUCCESS'
export const UPDATE_DISCOUNT_DRINK_FAILURE = 'UPDATE_DISCOUNT_DRINK_FAILURE'

export const GET_DRINK_NOT_PROMOTION_REQUEST = 'GET_DRINK_NOT_PROMOTION_REQUEST'
export const GET_DRINK_NOT_PROMOTION_SUCCESS = 'GET_DRINK_NOT_PROMOTION_SUCCESS'
export const GET_DRINK_NOT_PROMOTION_FAILURE = 'GET_DRINK_NOT_PROMOTION_FAILURE'